version: '3.4'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx-dev.conf:/etc/nginx/nginx.conf
      - web-root:/var/www/html
    links:
      - api
      - app
    depends_on:
      - api
      - app
  app:
    image: pp-fe:acceptance
    restart: always
    depends_on:
      - api
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:dbpassword@postgres/pingping
      CLAIM_URI: https://api.pingping.amsterdam/api/reward/validate/?uuid=
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=pingping
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
  web-root:
