version: '3.4'

services:
  app:
    image: pp-fe:latest
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:dbpassword@postgres/pingping
      CLAIM_URI: https://api.staging.pingping.refleks.tech/api/reward/validate/?uuid=
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=pingping
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  postgres_storage: