version: '3.4'

services:
  app:
    image: registry.gitlab.com/fleks-e43/municipality/backend-pp:dev
    build: .
    environment:
      DATABASE_URL: mysql://root:dbpassword@api.staging.pingping.refleks.tech/pingping
      WAIT_HOSTS: api.staging.pingping.refleks.tech:3306
      CLAIM_URI: https://api.staging.pingping.refleks.tech/api/reward/validate/?uuid=
    ports:
      - "8001:8000"
#     depends_on:
#       - db
#   db:
#     image: mysql:5.7.27
#     environment:
#       - MYSQL_ROOT_PASSWORD=dbpassword
#       - MYSQL_DATABASE=pingping
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_storage:/var/lib/mysql

# volumes:
#   db_storage: