version: '3.4'

services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - app
    depends_on:
      - api
      - app
  app:
    image: pp-fe:latest
  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:dbpassword@postgres/pingping
      CLAIM_URI: https://api.staging.pingping.refleks.tech/api/reward/validate/?uuid=
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=pingping
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql

volumes:
  postgres_storage: