version: '3.4'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - web-root:/var/www/html
    links:
      - api
    depends_on:
      - api
  api:
    build:
      context: .
      args:
        PORT: 8000
    restart: always
    environment:
      MONGO_STRING: mongodb://mongo:27017/pingping
      NUMBER_OF_PROCESSES: 4
    depends_on:
      - mongo
    ports:
      - '8000:8000'
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
  web-root:
