version: '3.4'

services:
  app:
    image: registry.gitlab.com/fleks-e43/municipality/backend-pp:latest
    environment:
      DATABASE_URL: mysql://root:dbpassword@db/pingping
      WAIT_HOSTS: db:3306
      CLAIM_URI: https://staging.pingping.refleks.tech.com/claim
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7.27
    environment:
      - MYSQL_ROOT_PASSWORD=dbpassword
      - MYSQL_DATABASE=pingping
    ports:
      - "3306:3306"
    volumes:
      - db_storage:/var/lib/mysql

volumes:
  db_storage: