# Generated by Django 2.2.4 on 2019-08-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_amount', models.FloatField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('descritption', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=255)),
                ('user_user_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
    ]
