# Generated by Django 2.2.4 on 2019-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='api.Task'),
        ),
    ]
