# Generated by Django 2.2.4 on 2019-08-13 16:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190812_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='conditions',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
