# Generated by Django 2.2.4 on 2019-08-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190814_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_user_key',
        ),
    ]
