# Generated by Django 2.2.4 on 2019-08-14 20:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_task_user_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='steps',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
