# Generated by Django 2.2.4 on 2019-08-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190815_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivement',
            name='unlock_date',
        ),
        migrations.RemoveField(
            model_name='achivement',
            name='user_user_key',
        ),
        migrations.CreateModel(
            name='AchivementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateField()),
                ('achivement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Achivement')),
                ('user_user_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
    ]
