# Generated by Django 2.2.4 on 2019-08-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190815_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tasks',
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Task')),
                ('user_user_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
    ]
