# Generated by Django 2.2.4 on 2019-08-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='descritption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='descritption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descritption',
            new_name='description',
        ),
    ]
