# Generated by Django 2.2.4 on 2019-08-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190815_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='user_user_key',
        ),
        migrations.CreateModel(
            name='RewardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Reward')),
                ('user_user_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.User')),
            ],
        ),
    ]
