# Generated by Django 2.2.4 on 2019-08-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190816_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('yesNo', 'Yes or No'), ('date', 'Date')], max_length=5)),
                ('yes_text', models.CharField(max_length=255)),
                ('not_text', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('not_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_not_id', to='api.Question')),
                ('yes_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q_yes_id', to='api.Question')),
            ],
        ),
    ]
