# Generated by Django 2.2.4 on 2019-08-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190821_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='not_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_not_id', to='api.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='yes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='q_yes_id', to='api.Question'),
        ),
    ]
