# Generated by Django 2.2.4 on 2019-08-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190821_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
