# Generated by Django 2.2.4 on 2019-08-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_question_question_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='not_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='yes_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
