# Generated by Django 2.2.4 on 2019-08-23 13:54

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190822_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarduser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='rewarduser',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Reward', validators=[api.models.validate_reward]),
        ),
    ]
