# Generated by Django 2.2.4 on 2019-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190823_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarduser',
            name='pdf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rewarduser',
            name='qr',
            field=models.TextField(blank=True),
        ),
    ]
