# Generated by Django 2.2.4 on 2019-08-23 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190823_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewarduser',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='rewarduser',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='rewarduser',
            name='uuid',
        ),
        migrations.AddField(
            model_name='reward',
            name='pdf',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
