# Generated by Django 2.2.4 on 2019-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_routetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_task',
            field=models.CharField(default='No text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='upload/media/'),
        ),
    ]
