# Generated by Django 2.2.4 on 2019-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190827_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='info',
            field=models.CharField(default='no info', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='success_m',
            field=models.CharField(default='success', max_length=255),
            preserve_default=False,
        ),
    ]
