# Generated by Django 2.2.4 on 2019-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190827_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achivement',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
