# Generated by Django 2.2.4 on 2019-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190827_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivementuser',
            name='unlock_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
