# Generated by Django 2.2.4 on 2019-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default='no name', max_length=45),
            preserve_default=False,
        ),
    ]
