# Generated by Django 2.2.4 on 2019-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190828_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/icons/'),
        ),
    ]
