# Generated by Django 2.2.4 on 2019-08-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190828_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/icons/'),
        ),
    ]
