# Generated by Django 2.2.4 on 2019-08-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190828_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetask',
            name='title',
        ),
    ]
