# Generated by Django 2.2.4 on 2019-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_routetask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetask',
            name='title',
            field=models.CharField(default='notitle', max_length=255),
            preserve_default=False,
        ),
    ]
