# Generated by Django 2.2.4 on 2019-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_routetask_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
