# Generated by Django 2.2.4 on 2019-08-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190828_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
