# Generated by Django 2.2.4 on 2019-08-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190828_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetask',
            name='card_icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Icon'),
        ),
    ]
