# Generated by Django 2.2.4 on 2019-08-29 18:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190829_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='steps',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
