# Generated by Django 2.2.4 on 2019-08-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20190829_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarduser',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
