# Generated by Django 2.2.4 on 2019-09-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rewarduser_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewarduser',
            name='validated',
        ),
    ]
