# Generated by Django 2.2.4 on 2019-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_rewarduser_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarduser',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
