# Generated by Django 2.2.4 on 2019-09-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rewarduser_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Task'),
        ),
    ]
