# Generated by Django 2.2.4 on 2019-09-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20190903_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuser',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskuser',
            unique_together={('user_user_key', 'task')},
        ),
    ]
