# Generated by Django 2.2.4 on 2019-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190905_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='on_complete',
            field=models.BooleanField(default=True),
        ),
    ]
