# Generated by Django 2.2.4 on 2019-09-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_achivement_on_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Icon'),
            preserve_default=False,
        ),
    ]
