# Generated by Django 2.2.4 on 2019-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190906_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('yesNo', 'Yes or No'), ('date', 'Date'), ('multipleOne', 'Multiple One')], max_length=5),
        ),
    ]
