# Generated by Django 2.2.4 on 2019-09-16 19:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190916_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
