# Generated by Django 2.2.4 on 2019-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190916_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('yesNo', 'Yes or No'), ('date', 'Date'), ('multipleOne', 'Multiple One')], max_length=11),
        ),
    ]
