# Generated by Django 2.2.4 on 2019-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190916_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
