# Generated by Django 2.2.4 on 2019-09-18 14:26

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190918_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='steps',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
