# Generated by Django 2.2.4 on 2019-09-18 14:30

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190918_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='steps',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
